# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-05-22 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedinuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
