# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-05-24 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=31)),
            ],
        ),
    ]
